# 使用官方提供的基础镜像
FROM alpine:latest

# 设置工作目录
WORKDIR /app

# 将压缩包复制到容器中
COPY binary/amd64/app.tar.gz /app/

# 解压压缩包
RUN tar -xzvf app.tar.gz

# 清理工作目录，减少镜像大小
RUN rm app.tar.gz

# 定义容器启动时执行的命令
ENTRYPOINT ["/app/netlink"]
